FROM mysql:latest
WORKDIR /
ENV MYSQL_ROOT_PASSWORD=urubu100
COPY ./BancoDeDados/script-gatewatch.sql .
EXPOSE 3306

FROM node:lts-bookworm AS dependencies
WORKDIR /app
COPY package.json .
RUN npm install

FROM node:lts-apline3.20 AS deploy
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
EXPOSE 3333
CMD ["node", "app.js"]